name: Deploy to Minikube

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup kubectl
      run: |
        curl -LO https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl
        chmod +x kubectl && sudo mv kubectl /usr/local/bin/kubectl

    - name: Deploy to Minikube
      run: |
        minikube start --driver=docker
        kubectl apply -f blue/
