apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
    version: blue     # 👈 Change to "green" when switching
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
